name: MMLeaderboard
version: '${project.version}'
main: me.lehreeeee.mmleaderboard.MMLeaderboard
api-version: '1.20'
commands:
  mmleaderboard:
    description: Starts tracking entity for leadeboard.
    usage:
    - /mml [add/remove] <UUID>
    - /mml list
    aliases: mml
    permission: mml.admin
    permission-message: You need permission for that!